---
crons:
  - name: Uptime CI
    'on':
      schedule:
        - cron: '*/5 * * * *'
  - name: Updates CI
    'on':
      schedule:
        - cron: '*/30 * * * *'
  - name: Graphs CI
    'on':
      schedule:
        - cron: '*/30 * * * *'
  - name: Response Time CI
    'on':
      schedule:
        - cron: '*/30 * * * *'
  - name: Summary CI
    'on':
      schedule:
        - cron: 30 0/3 * * *
  - name: Static Site CI
    'on':
      schedule:
        - cron: 0 0/3 * * *
# Change these first
owner: keyper-labs
repo: palmera-services-status
sites:
  - name: Palmera Tx Service (Chronicle Yellowstone Testnet)
    url: https://prod.chronicle-yellowstone.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Chronicle Yellowstone Testnet)
    url: https://prod.chronicle-yellowstone-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Degen)
    url: https://prod.degen.keypersafe.xyz/check/
  - name: Palmera Tx Service (Flare)
    url: https://prod.flare.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Flare)
    url: https://prod.flare-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Form)
    url: https://prod.form.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Form)
    url: https://prod.form-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Goat Network)
    url: https://prod.goat-network.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Goat Network)
    url: https://prod.goat-network-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Neox)
    url: https://prod.neox.transaction.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Neox)
    url: https://prod.neox-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Neox Testnet)
    url: https://prod.neox-t.transaction.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Zeronet)
    url: https://prod.wl-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Zeronet)
    url: https://prod.zeronet-mainnet.transaction.keypersafe.xyz/check/
  - name: Palmera Tx Service (Somnia Testnet)
    url: https://prod.somnia-testnet.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Somnia Testnet)
    url: https://prod.somnia-testnet-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Perennial)
    url: https://prod.perennial.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Perennial)
    url: https://prod.perennial-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Matchain)
    url: https://prod.matchain.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Matchain)
    url: https://prod.matchain-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Hedera Mainnet)
    url: https://prod.hedera-mainnet.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Hedera Mainnet)
    url: https://prod.hedera-mainnet-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Hedera Testnet)
    url: https://prod.hedera-testnet.keypersafe.xyz/check/
  - name: Palmera Tx Service (Coti Mainnet)
    url: https://prod.coti-mainnet.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Coti Mainnet)
    url: https://prod.coti-mainnet-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Hyperliquid)
    url: https://prod.hyperliquid.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Hyperliquid)
    url: https://prod.hyperliquid-client-gateway.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Z-Chain)
    url: https://prod.z-chain.keypersafe.xyz/check/
  - name: Palmera Client Gateway (Z-Chain)
    url: https://prod.z-chain-client-gateway.keypersafe.xyz/health/ready/
skipTopicsUpdate: true
status-website:
  # baseUrl: /palmera-services-status
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.palmeradao.xyz
  favicon: https://app.palmeradao.xyz/favicon.ico
  introMessage: Palmera Infrastructure Status
  introTitle: Status for the **Palmera Infrastructure**
  logoUrl: https://2047386747-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F5XJ6DPuAnCiNORg51ulK%2Fuploads%2Fqa0DwfBMwvw2oeITSqX4%2FPalmera-Sunset%20Logo.jpg?alt=media&token=ef3743e0-3a04-4fc4-98a4-fdc34efbf9cc
  name: Palmera Infrastructure Status
  navbar:
    - href: https://tx-status.palmeradao.xyz/
      title: Indexing Status
    - href: https://palmeradao.xyz/deploy-safe-chain
      title: Palmera Infrastructure
    - href: https://docs.palmeradao.xyz/
      title: Dev docs
