---
# Change these first
owner: keyper-labs
repo: palmera-services-status
sites:
  - name: Palmera Client Gateway
    url: https://client-gateway-prod.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Mainnet)
    url: https://prod.mainnet.transaction.keypersafe.xyz/check/
  - name: Palmera Tx Service (Gnosis Chain)
    url: https://prod.gnosis.keypersafe.xyz/check/
  - name: Palmera Tx Service (Sepolia)
    url: https://dev.sepolia2.transaction.keypersafe.xyz/check/
  - name: Palmera Tx Service (Polygon - Matic)
    url: https://prod.polygon.transaction.keypersafe.xyz/check/
  - name: Palmera Tx Service (Base Mainnet)
    url: https://prod.base.keypersafe.xyz/check/
  - name: Palmera Tx Service (Celo)
    url: https://prod.celo.keypersafe.xyz/check/
  - name: Palmera Tx Service (Arbitrum)
    url: https://prod.arbitrum.keypersafe.xyz/check/
  - name: Palmera Tx Service (Optimism)
    url: https://prod.optimism.keypersafe.xyz/check/
  - name: Palmera Tx Service (Treasure)
    url: https://prod.treasure.keypersafe.xyz/check/
  - name: Palmera Tx Service (Arthera)
    url: https://prod.arthera.transaction.keypersafe.xyz/check/
skipTopicsUpdate: true
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: uptime.keypersafe.xyz
  favicon: https://app.palmeradao.xyz/favicon.ico
  introMessage: Palmera Services Status
  introTitle: Status for the **Palmera Services**
  baseUrl: /palmera-services-status
  logoUrl: https://2047386747-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F5XJ6DPuAnCiNORg51ulK%2Fuploads%2FpNt05Qf4ymTQqESZAa2A%2FPalmeraLogo_Black.png?alt=media&token=f25b330f-3056-47c9-92ce-d55ce4133728
  name: Palmera Services Status
  navbar:
    - href: https://status.palmeradao.xyz
      title: Indexing Status
    - href: https://palmeradao.xyz/deploy-safe-chain
      title: Palmera Infrastructure
    - href: https://docs.palmeradao.xyz/
      title: Dev docs