# Change these first
owner: Palmera Dao # Your GitHub organization or username, where this repository lives
repo: palmera-services-status # The name of this repository
skipTopicsUpdate: true
sites:
  - name: Palmera Client Gateway
    url: https://client-gateway-prod.keypersafe.xyz/health/ready/
  - name: Palmera Tx Service (Mainnet)
    url: https://prod.mainnet.transaction.keypersafe.xyz/check/
  - name: Palmera Tx Service (Gnosis Chain)
    url: https://prod.gnosis.keypersafe.xyz/check/
  - name: Palmera Tx Service (Sepolia)
    url: https://dev.sepolia2.transaction.keypersafe.xyz/check/
  - name: Palmera Tx Service (Polygon - Matic)
    url: https://prod.polygon.transaction.keypersafe.xyz/check/
  - name: Palmera Tx Service (Base Mainnet)
    url: https://prod.base.keypersafe.xyz/check/
  - name: Palmera Tx Service (Celo)
    url: https://prod.celo.keypersafe.xyz/check/
  - name: Palmera Tx Service (Arbitrum)
    url: https://prod.arbitrum.keypersafe.xyz/check/
  - name: Palmera Tx Service (Optimism)
    url: https://prod.optimism.keypersafe.xyz/check/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.keypersafe.xyz
  # baseUrl: /palmera-services-status
  logoUrl: https://pbs.twimg.com/profile_images/1643941027898613760/gyhYEOCE_400x400.jpg
  name: Palmera Services Status
  introTitle: Status for the **Palmera Services**
  introMessage: Palmera Services Status
  favicon: https://app.palmeradao.xyz/favicon.ico
  navbar:
    - title: Indexing Status
      href: https://status.palmeradao.xyz
    - title: Palmera Infrastructure
      href: https://www.palmeradao.xyz/deploy-safe-chain
    - title: Dev docs
      href: https://docs.palmeradao.xyz/